version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    container_name: rps_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: rps
      POSTGRES_PASSWORD: rps1234
    ports:
      - "5435:5432"
    volumes:
      - RPS_data:/var/lib/postgresql/data
volumes:
  RPS_data:
